name: flutter_module_1
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_riverpod: ^2.4.10
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  uuid: ^4.3.3
  camera: ^0.10.5+9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  module:
    androidX: true
    androidPackage: com.example.flutter_module_1
    iosBundleIdentifier: com.example.flutterModule1
